= The Report

== Introduction

During the course DevOps, Software Evolution and Software Maintenance an application stemming from an earlier course
has been subjected to a simulation simulating real world usage by users. This has forced us to make the application more
durable, more performant, and more maintainable. This has taught us to develop more performant applications, implement 
robust CI/CD workflows, and to use metrics, monitoring and logging to monitor, and keep our application healthy.

== System's Perspective

=== Design and Architecture of ITU-MiniTwit Systems

// Description and illustration of the design and architecture.

=== Dependencies of ITU-MiniTwit Systems

// List and brief description of all technologies and tools applied and depended on.

=== Important Interactions of Subsystems

// Description of important interactions of subsystems.

=== Current State of Systems

// Description of the current state of systems.

== Process' Perspective

=== CI/CD Chains

// Description of stages and tools included in the CI/CD chains.

=== System Monitoring

// Description of how the systems are monitored and what is monitored.

=== System Logging

We did not have success with using the ELK stack.
For that reason, we chose to use a proprietary logging and application Performance Monitoring system called New Relic.
New Relic logs everything written to the nodes console, and this allowed us to have the same level of logging, as if we were debugging on our local machine.
When the application failed to process a request, the stacktrace and message from encountered exceptions, as well as the events leading
up to them, would be logged.

This provided us with the ability to see the frequency at which different API endpoints where accessed, the actions taken
by the server to process the request, as well as errors when requesting a resource from our application.

Downloading and launching of the New Relic Agent was included in our dockerfile, and thus logging was done on all the nodes
in our application cluster.

// Description of what is logged in the systems and how logs are aggregated.

=== Security Assessment

// Brief results of the security assessment and description of how the system security was hardened.

=== Scaling and Upgrades Strategy

// Description of the applied strategy for scaling and upgrades.

=== Use of AI-Assistants
In this project these AI-assistants were used:

* OpenAI's ChatGPT version 3.5, 4.0.
* GitHub Copilot

The AI-assistants were mainly used for:

* Breaking down code logic. I.g. In order to recreate the Python API controller provided by the course, the code needed to be translated into C#. ChatGPT was a fitting tool for this task, as it could quickly provide translations. 
* Code completions. GitHub Copilot acted as an extension of IntelliSense, in the sense that it could auto-complete simple pieces of code, such as loops, if-statements, and method signatures.
* Research. ChatGPT was also used to provide a secondary explanation when researching new technologies, in situations were the documentation either was difficult to understand, or if subsidary information was needed. 
* Stacktrace breakdowns. ChatGPT was used to breakdown stracktraces, summarizing the information as well as providing a more user-friendly format to read. 
* Identify functions that could be made more performant. 

Downsides of using AI-assistants:

* Both ChatGPT and Github Copilot are flawed, which makes them unreliable tools. Sometimes it would take as much time to doublecheck the output of an assistant as would have to complete the task without it, which defeats the purpose of using them.
* If used without careful inspeciton of the provided code, the LLM is likely to introduce bugs into the application. This is due to the fact,
that LLM's have a difficult time understanding the context in which the requested code is supposed to operate.

// Description of the use of AI-assistants during the project.

== Lessons Learned Perspective

=== Evolution and Refactoring

// Description of the biggest issues, how they were solved, and lessons learned.

=== Operation

// Description of the biggest issues, how they were solved, and lessons learned.

=== Maintenance

// Description of the biggest issues, how they were solved, and lessons learned.

== DevOps Style of Work
Agile principles \\
Psychological safety \\
Pair programming/mob programming \\
Kanbanboard/Github project board\\
// Reflection and description of the "DevOps" style of work.

== Conclusion

// Brief conclusion of the report.

== References

// List of references.