FROM mcr.microsoft.com/mssql/server:2022-latest

# Copy the current directory contents into the /Configuration directory in the container
COPY ./src/Configuration ./Configuration

# Temporarily switch to root to change file permissions
USER root
RUN chmod +x /Configuration/entrypoint.sh
RUN chmod +x /Configuration/configure-db.sh
# Switch back to the mssql user (or use the specific UID if known)
USER mssql

# Set the working directory to /Configuration
WORKDIR /Configuration

# Execute the entrypoint script
ENTRYPOINT ["/Configuration/entrypoint.sh"]
