version: "3.8"
services:

  minitwit:
    container_name: webserver
    image: minitwitimage:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file:
      - .env
    networks: 
      - minitwit-network
    command: [ "dockerize", "-wait", "tcp://database:3306", "-timeout", "30s", "./start-webserver.sh" ]
  
  prometheus_server:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - minitwit-network
  
networks:
    minitwit-network:
        name: minitwit-network
        

