version: "3.8"
services:

  minitwit:
    container_name: webserver
    image: minitwitimage:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file:
      - .env
    networks: 
      - minitwit-network