version: "3.8"
services:
  
  minitwit_database:
    container_name: database
    image: mysql:latest
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - minitwit-network

  minitwit:
    container_name: webserver
    image: minitwitimage:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file:
      - .env
    networks: 
      - minitwit-network
    command: [ "dockerize", "-wait", "tcp://database:3306", "-timeout", "30s", "./start-webserver.sh" ]

networks:
    minitwit-network:
        name: minitwit-network  