version: "3.8"
volumes:
  prometheus-data: {}
  grafana-data: {}

services:
  
  minitwit:
    container_name: webserver
    image: minitwitimage:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file:
      - .env
    networks: 
      - minitwit-network
    command: [ "dockerize", "-wait", "tcp://database:3306", "-timeout", "30s", "./start-webserver.sh" ]
  
  prometheus_server:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - minitwit-network
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
        
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - minitwit-network
    
  
networks:
    minitwit-network:
        name: minitwit-network
        

