version: "3.8"
services:
  
  minitwit_database:
    container_name: database
    #Sql server docker image package name
    image: minitwit-database
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - minitwit-network

  minitwit:
    container_name: webserver
    image: minitwit
    ports:
      - "8080:8080"
      - "8081:8081"
    networks: 
      - minitwit-network
  
networks:
    minitwit-network:
        name: minitwit-network
        external: false
        