name: AsciiDoc to PDF

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0' # Adjust the Ruby version if needed

    - name: Install AsciiDoctor and dependencies
      run: |
        gem install asciidoctor-pdf
        gem install rouge
        gem install matrix

    - name: Convert AsciiDoc to PDF
      run: asciidoctor-pdf report/index.adoc