name: AsciiDoc to PDF

on:
  push:
    branches:
      - main
    paths:
      - '*.adoc' 
      - '**/*.png' 
      - '**/*.jpg' 
      - '**/*.gif'

jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3

    - name: Install AsciiDoctor
      run: gem install asciidoctor-pdf

    - name: Convert AsciiDoc to PDF
      run: asciidoctor-pdf -o report/build/report.pdf report/index.adoc