  name : Automatic Release
  on:
    schedule:
      # - Time of day
    - cron: '56 16 * * 4'
  
  #Fetches the latest tag from the repository
  #git describe --abbrev=0 --tags
  jobs:
   release:
      runs-on: ubuntu-latest
      name: automatic release of main branch
          
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
          
        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '8.0.x'

        - name: Restore Dependencies
          run: dotnet restore src/Minitwit.Web

        - name: Build
          run: |
            tag=${git describe --tag --abbrev=0}

            targets=("osx-arm64" "osx-x64" "win-x64" "linux-x64")
            for target in "${targets[@]}"
            do
              release_name="Minitwit-$tag-$target"
              dotnet publish src/Minitwit.Web/ -c Release --framework net8.0 --runtime $target -o "$release_name"
            
              7z a -tzip "${release_name}.zip" "./${release_name}/*"
  
              rm -r "$release_name"
            done

        - name: Publish
          uses: softprops/action-gh-release@v1
          with:
            files: |
              Minitwit*.zip
              Minitwit*.tar.gz
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      
        
