  name : Automatic Release
  on:
    schedule:
      # - Time of day
    - cron: '56 16 * * 4'
  
  #Fetches the latest tag from the repository
  #git describe --abbrev=0 --tags
  jobs:
   release:
      runs-on: ubuntu-latest
      name: automatic release of main branch
          
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
          
        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '8.0.x'

        - name: Restore Dependencies
          run: dotnet restore src/Minitwit.Web

        - name: Build
          run: |
            tag=${git describe --tag --abbrev=0}

            targets=("osx-arm64" "osx-x64" "win-x64" "linux-x64")
            for target in "${target[@]}"
            do
              release_name="Minitwit-"
          
          
      
        
