name: .NET Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore src/Minitwit.Web
    - name: Build
      run: dotnet build src/Minitwit.Web --no-restore
    - name: Test
      run: |
        dotnet test test/Minitwit.CoreTests
        dotnet test test/Minitwit.InfrastructureTests
        dotnet test test/Minitwit.WebTests

    - name: Format and lint code
      run: |
        dotnet new tool-manifest
        dotnet tool install csharpier
        dotnet csharpier .
        dotnet format -v detailed .
        echo "Code formatting and linting complete."

    - name: Commit and push if needed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add -A
        git diff --staged --quiet || git commit -m 'Automated code format and linting'
        git push
