name: .NET Build and Release

permissions:
  contents: write

on:
  schedule:
  #- 16:56 every Thursday
  - cron: '49 20 * * 4'

jobs:
  build-and-release:
    name: Cross-Compile on ubuntu-latest and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore src/Minitwit.Web

      - name: Build
        run: |
          tag=$(git describe --tags --abbrev=0)

          # Declare an array of runtime targets
          targets=("osx-arm64" "osx-x64" "win-x64" "linux-x64")
          
          # Iterate through the targets and create executables for each
          for target in "${targets[@]}"
          do
            release_name="Minitwit-$tag-$target"
            dotnet publish src/Minitwit.Web/ -c Release --framework net8.0 --runtime $target -o "$release_name"
          
            7z a -tzip "${release_name}.zip" "./${release_name}/*"

            rm -r "$release_name"
          done

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Minitwit*.zip
            Minitwit*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
